export const categoryMap = {
  All: 'trending',
  Gaming: 'gaming',
  Songs: 'songs',
  Cricket: 'cricket highlights',
  Cooking: 'cooking recipes',
  Soccer: 'football',
  News: 'latest news',
  Movies: 'movie trailers',
  Technology: 'technology',
  Fashion: 'fashion',
  Comedy: 'comedy',
  Travel: 'travel vlog',
  Education: 'education',
  Documentary: 'documentary',
  Music: 'music',
  Sports: 'sports',
  jokes: 'funny videos',
};
